### ISSUE TITLE
Optifine crashes with Antsportation on 1.18.2

### ISSUE THREAD

**Issue by Archspect** [Matyrobbrt/Antsportation#2]
Operating system: Arch Linux x86_64
Minecraft Version: 1.18.2
Mods installed alongside: Create, Optifine, Xaero's Minimap, JEI, Flywheel.
This issue occurs upon creating a new world.
Crash report 

```
[20:20:21] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing start region for dimension minecraft:overworld
[20:20:21] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'void net.minecraft.server.level.DistanceManager.addRegionTicket(net.minecraft.server.level.TicketType, net.minecraft.world.level.ChunkPos, int, java.lang.Object, boolean)'
	at net.minecraft.server.level.ServerChunkCache.addRegionTicket(ServerChunkCache.java:429) ~[client-1.18.2-20220404.173914-srg.jar%2360!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_8387_(ServerChunkCache.java:425) ~[client-1.18.2-20220404.173914-srg.jar%2360!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129940_(MinecraftServer.java:471) ~[client-1.18.2-20220404.173914-srg.jar%2360!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:318) ~[client-1.18.2-20220404.173914-srg.jar%2360!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%2360!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.18.2-20220404.173914-srg.jar%2360!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2360!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}
[20:20:22] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 3a623b44-3291-4691-8436-3f6e5dd8b48d
[20:20:23] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 050dc8b3-5c77-45b0-b3a9-7faa67f754d7
[20:20:23] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /home/archspect/.local/share/multimc/instances/1.18.2/.minecraft/crash-reports/crash-2022-07-30_20.20.22-server.txt
[20:20:23] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[20:20:23] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[20:20:23] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[20:20:23] [Render thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 08423903-dccb-4833-ba43-7fea0f7d16b4
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 7/30/22, 8:20 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'void net.minecraft.server.level.DistanceManager.addRegionTicket(net.minecraft.server.level.TicketType, net.minecraft.world.level.ChunkPos, int, java.lang.Object, boolean)'
	at net.minecraft.server.level.ServerChunkCache.addRegionTicket(ServerChunkCache.java:429) ~[client-1.18.2-20220404.173914-srg.jar%2360!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_8387_(ServerChunkCache.java:425) ~[client-1.18.2-20220404.173914-srg.jar%2360!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129940_(MinecraftServer.java:471) ~[client-1.18.2-20220404.173914-srg.jar%2360!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:318) ~[client-1.18.2-20220404.173914-srg.jar%2360!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%2360!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.18.2-20220404.173914-srg.jar%2360!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2360!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version 5.15.55-1-lts
	Java Version: 18.0.2, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1727689080 bytes (1647 MiB) / 2583691264 bytes (2464 MiB) up to 3925868544 bytes (3744 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
	Identifier: Intel64 Family 6 Model 42 Stepping 7
	Microarchitecture: Sandy Bridge (Client)
	Frequency (GHz): 3.30
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: 2nd Generation Core Processor Family Integrated Graphics Controller
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x0102
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 2906.59
	Virtual memory used (MB): 4576.19
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms128m -Xmx3744m
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:forge, mod:flywheel (incompatible), mod:create, mod:xaerominimap, mod:antsportation, mod:jei (incompatible)
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	OptiFine Version: OptiFine_1.18.2_HD_U_H6
	OptiFine Build: 20220313-160847
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 3.3 (Core Profile) Mesa 22.1.3
	OpenGlRenderer: Mesa Intel(R) HD Graphics 2000 (SNB GT1)
	OpenGlVendor: Intel
	CpuCount: 4
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.18.2-40.1.60-universal.jar                |Forge                         |forge                         |40.1.60             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		flywheel-forge-1.18-0.6.3.jar                     |Flywheel                      |flywheel                      |1.18-0.6.3.81       |DONE      |Manifest: NOSIGNATURE
		create-mc1.18.2_v0.5.0.jar                        |Create                        |create                        |0.5.0               |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_22.7.0_Forge_1.18.2.jar            |Xaero's Minimap               |xaerominimap                  |22.7.0              |DONE      |Manifest: NOSIGNATURE
		antsportation-1.18.2-1.1.1.jar                    |Antsportation                 |antsportation                 |1.1.1               |DONE      |Manifest: NOSIGNATURE
		jei-1.18.2-forge-10.1.3.240.jar                   |Just Enough Items             |jei                           |10.1.3.240          |DONE      |Manifest: NOSIGNATURE
	Flywheel Backend: Off
	Crash Report UUID: 08423903-dccb-4833-ba43-7fea0f7d16b4
	FML: 40.1
	Forge: net.minecraftforge:40.1.60
#@!@# Game crashed! Crash report saved to: #@!@# /home/archspect/.local/share/multimc/instances/1.18.2/.minecraft/crash-reports/crash-2022-07-30_20.20.22-server.txt
[20:20:23] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[Antsportation]'/minecraft:overworld
[20:20:24] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[Antsportation]'/minecraft:the_nether
[20:20:24] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[Antsportation]'/minecraft:the_end
[20:20:24] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (Antsportation): All chunks are saved
[20:20:24] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[20:20:24] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[20:20:24] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage: All dimensions are saved
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 255.
```

**Comment by Matyrobbrt** [comment]
Have you tried *without* OptiFine? My guess here is that it is overriding a forge patch.

**Comment by Matyrobbrt** [comment]
The issue here is OptiFine not being compatible with the changes in https://github.com/MinecraftForge/MinecraftForge/pull/8784
